config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"

  resources :users

  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:user_name, :email)
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find_by_id(params[:id])
    @post = Post.find_by_id(params[:post_id])
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @post = Post.find_by_id(params[:post_id])
    @user = current_user
  end

  # GET /comments/1/edit
  def edit
    @post = Post.find_by_id(params[:post_id])
    @comment = Comment.find_by_id(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @post = Post.find_by_id(params[:post_id])
    @comment.post = @post
    @user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @post = Post.find_by_id(params[:post_id])
    @comment = Comment.find_by_id(params[:id])
    @user = current_user

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
# DOES NOT WORK
  def destroy
    @post = Post.find_by_id(params[:post_id])
    @comment = Comment.find_by_id(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by_id(params[:id])
    @user = User.find_by_id(@post.user_id)
  end

  # GET /posts/new
  def new
    @post = Post.new
    @user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @user = current_user

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :comment_id, :post_image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @posts = Post.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_id(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :password, :post_id, :comment_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<div class="comment-card card">
  <h3 class="center">Comment</h3>
  <%= form_for [@post, @comment] do |f| %>

    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:
        </h2>
        <ul>
          <% comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="card row">
      <div class="post-details col l8 m6 s12">
        <div class="row">
          <div class="author-image s6 left">
            <img class="responsive-img hero-image" src="<%= current_user.profile_picture %>" alt="member profile image goes here" />
          </div>
          <div class="author-details-post-date s6 right">
            <div class="post-author col s12">
              <b>Author: </b> <%= link_to "#{current_user.user_name}", user_path(current_user.id), class: "link-text" %>
            </div>
            <div class="post-author col 12">
              <b>Posted: </b><%= current_user.created_at.to_date %>
            </div>
          </div>
        </div>
        <div class="post-title center col s12">
          <h2><%= @post.title %></h2>
        </div>
        <div class="post-content col s12">
          <h6><%= @post.content %></h6>
        </div>
      </div>
      <div class="image col l4 m6 s12">
        <img class="responsive-image" src="<%= @post.post_image %>" alt="post image" />
      </div>
    </div>

    <div class="field">
      <%= f.label :content %>
      <%= f.text_field :content %>
    </div>

    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>

    <div class="actions">
      <%= button_tag(type: 'submit', :class => 'waves-effect waves-light btn') do %>
        <i class="material-icons left">done</i>Save
      <% end %>
    </div>

  <% end %>

</div>

app/views/comments/edit.html.erb
<%= render 'form', comment: @comment %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@comment) %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sneaker Seeker</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bungee+Inline|Raleway" rel="stylesheet">
  </head>

  <body>
    <nav>
      <div class="navbar-fixed">
        <a href="/posts" class="brand-logo center grey-text lighten-4">Sneaker Seeker</a>
        <a href="#" data-activates='dropdown' class="button-collapse dropdown-button grey-text lighten-4"><i class="material-icons">menu</i></a>

        <!-- full sized navigation options -->
        <ul class="left hide-on-med-and-down">
          <% if current_user %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% end %>

          <% if !current_user %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>

        <!-- navigation dropdown list for small screen -->
        <ul class="dropdown-content grey-text lighten-4" id="dropdown">
          <% if current_user %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% end %>

          <% if !current_user %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>

        </ul>
      </div>
    </nav>

    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="new-post card">

<h3 class="center">Post</h3>

<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_image %>
    <%= f.text_field :post_image, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control materialize-textarea"%>
  </div>

  <% if !current_user %>
    <div class="field">
      <%= f.hidden_field :user_id, :value => @user.id %>
    </div>
  <% else %>
    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user %>
  <div class="add-comment">
    <%= link_to new_post_path, :class => 'waves-effect waves-light btn' do %>
      <i class="material-icons left">comment</i>New Post
    <% end %>
  </div>
<% end %>

<div>
  <% @posts.each do |post| %>
    <div class="row card post-show-card">
      <div class="post-details col s12 m6 l8 <%= post.id % 2 == 0 ? "left" : "right" %>">
        <div class="row">
          <div class="author-image s6 <%= post.id % 2 == 0 ? "left" : "right" %>">
            <img class="responsive-img" src="<%= post.user.profile_picture %>" alt="member profile image goes here" />
          </div>
          <div class="post-author col s6">
            <b>Author: </b><%= link_to "#{post.user.user_name}", user_path(post.user_id), class: "link-text" %>
          </div>
          <div class="post-author col s6">
            <b>Posted: </b><%= post.created_at.to_date %>
          </div>
        </div>
        <div class="post-title center col s12">
          <h4><b><%= link_to "#{post.title}", post_path(post.id), class: "link-text" %></b></h4>
        </div>
        <div class="post-content col s12 center">
          <h6><%= post.content %></h6>
        </div>
      </div>
      <div class="image col l4 m6 s12 <%= post.id % 2 == 0 ? "left" : "right" %>">
        <img class="responsive-image" src="<%= post.post_image %>" alt="post image" />
      </div>
      <% if post.comments.last %>
        <div class="post-comment">
          <div class="card col s12 z-depth-3">
              <div class="row">
                <div class="comment-author-image s3 m1 left">
                  <img class="responsive-img" src="<%= post.comments.last.user.profile_picture %>" alt="member profile image goes here" />
                </div>
                <div class="comment-author col s7">
                  <b>Author: </b><%= link_to "#{User.find_by_id(post.comments.last.user_id).user_name}", user_path(post.comments.last.user_id), class: "link-text" %>
                  <div class="comment-content col s12">
                    <%= post.comments.last.content %>
                  </div>
                </div>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<% if current_user %>
  <div class="add-comment2">
    <%= link_to new_post_path, :class => 'waves-effect waves-light btn' do %>
      <i class="material-icons left">comment</i>New Post
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row card post-show-card">
  <div class="post-details col l8 m6 s12">
    <div class="row">
      <div class="author-image s6 left">
        <img class="responsive-img hero-image" src="<%= @user.profile_picture %>" alt="member profile image goes here" />
      </div>
      <div class="author-details-post-date s6 right">
        <div class="post-author col s12">
          <b>Author: </b> <%= link_to "#{@user.user_name}", user_path(@user.id), class: "link-text" %>
        </div>
        <div class="post-author col 12">
          <b>Posted: </b><%= @user.created_at.to_date %>
        </div>
      </div>
    </div>
    <div class="post-title center col s12">
      <h2><b><%= @post.title %></b></h2>
    </div>
    <div class="post-content col s12">
      <h6><%= @post.content %></h6>
    </div>
  </div>
  <div class="image col l4 m6 s12">
    <img class="responsive-image" src="<%= @post.post_image %>" alt="post image" />
  </div>

  <% if current_user %>
    <% if current_user.id === @post.user_id %>
      <div class="row">
        <div class="col s6 left">
          <%= link_to edit_post_path(@post), :class => 'waves-effect waves-light btn' do %>
            <i class="material-icons left">create</i>Edit
          <% end %>
        </div>
        <div class="col s6 right">
          <%= link_to post_path(@post), method: :delete, :class => 'waves-effect waves-light btn right', data: { confirm: "Dude, you sure you want to dump those kicks!?" }  do %>
            <i class="material-icons right">delete</i>Delete
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

<% if current_user %>
  <div class="add-comment">
    <%= link_to new_post_comment_path(@post, @comment), :class => 'waves-effect waves-light btn' do %>
      <i class="material-icons left">comment</i>Add Comment
    <% end %>
  </div>
<% end %>

<div class="comments-title">
  <h4>Comments</h4>
</div>

<% if @post.comments.count > 0 %>
  <div class="card comment-area col s12">
    <% @post.comments.each do |comment| %>
      <div class="post-comment col s12">
        <div class="row">
          <div class="comment-image col s3 m1 left">
            <img class="responsive-img" src="<%= User.find_by_id(comment.user_id).profile_picture %>" alt="member profile image goes here" />
          </div>
          <div class="comment-author col s7">
            <b>Author: </b><%= link_to "#{User.find_by_id(comment.user_id).user_name}", user_path(User.find_by_id(comment.user_id)), class: "link-text" %>
            <div class="comment-content col s12">
              <%= comment.content %>
            </div>
          </div>
        </div>

        <% if current_user %>
          <% if current_user.id === comment.user_id %>
            <div class="comment-buttons row">
              <div class="col s6 left">
                <%= link_to edit_post_comment_path(@post, comment), :class => 'waves-effect waves-light btn' do %>
                  <i class="material-icons left">create</i>Edit Comment
                <% end %>
              </div>
              <div class="col s6 right">
                <%= link_to post_comment_path(@post, comment), method: :delete, :class => 'waves-effect waves-light btn right', data: { confirm: "Dude, you sure you want to drop that comment!?" }  do %>
                  <i class="material-icons right">delete</i>Delete Comment
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>

      </div>
    <% end %>
  </div>

<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_picture %>
    <%= f.text_field :profile_picture %>
  </div>

  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Index</h1>

<div id="users">
  <% @users.each do |user| %>
    <div class="user-card card">
      <div class="row">
        <div class="col s3">
          <a href="#{user.profile_picture}"></a>
        </div>
        <div class="col s9">
          <div class="user-details">
            <div class="col s12 user-name center">
              <%= user.user_name %>
            </div>
            <div class="col s4">
              <b>Join Date: </b><%= user.created_at.to_formatted_s(:db) %>
            </div>
            <div class="col s4">
              <b>Post Count: </b><%= %>
            </div>
            <div class="col s4">
              <b>Comment Count: </b><%= %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if user.posts.count %>
      <div class="recent-post">
        <div class="recent-post-title">
          Most Recent Post
        </div>
        <div class="recent-post-details">
          <%= @posts.all.find_by_id(user.user_id).title %>
          <br>
          <%= @posts.all.find_by_id(user.user_id).content %>
        </div>
      </div>
    <% end %>
    <%= link_to 'Show', user %>
    <%= link_to 'Edit', edit_user_path(user) %>
    <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

<br>
<div class="card hoverable">
  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="user-space">
  <div class="card post-show-card col m9 s12">
    <div class="post-details">
      <div class="row">
        <div class="author-image2 s4 left">
          <img class="responsive-img" src="<%= @user.profile_picture %>" alt="member profile image goes here" />
        </div>
        <div class="author-details-post-date s8 right">
          <div class="post-author-name col s12">
            <%= @user.user_name %>
          </div>
          <div class="post-author-date col s12">
            <b>Member Since: </b><%= @user.created_at.to_date %>
          </div>
          <div class="col s12">
            <b>Posts: </b><%= @user.posts.all.count %>
          </div>
          <div class="col s12">
            <b>Comments: </b><%= @user.comments.all.count %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="profile-picture col m3 s12">
    <a href="#{@user.profile_picture}"></a>
  </div>

  <% if current_user %>
    <% if current_user.id === @user.id %>
      <div class="row">
        <div class="user-edit s2 left">
          <%= link_to edit_user_path(@user), :class => 'waves-effect waves-light btn' do %>
            <i class="material-icons left">create</i>Edit
          <% end %>
        </div>
        <div class="user-delete s2 right">
          <%= link_to user_path(@user), action: "destroy", :class => 'waves-effect waves-light btn', data: { confirm: "Don't do it!  We'll miss you too much!" }  do %>
            <i class="material-icons right">delete</i>Delete
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>

</div>